package me.simon.testapp.weatherforecast;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.List;

/**
 * @author Simon Brebeck on 04/07/2023
 * Data Access Object for WeatherForecast
 * Manages access to the database for WeatherForecast
 */
public interface WeatherForecastDAO extends JpaRepository<WeatherForecast, Long> {

    // Add custom methods here like this:
    @Query("SELECT w FROM WeatherForecast w WHERE w.city = ?1")
    WeatherForecast findByCity(String city);

    // Or you can use derived query methods (query generated by method name) like this:

    /**
     * Find all WeatherForecasts between two dates
     * @param startDate the start date
     * @param endDate the end date
     * @return List of WeatherForecasts
     */
    List<WeatherForecast> findAllByDateBetween(Date startDate, Date endDate);


}
